spring:
  application:
    name: econavi
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace