spring:
  jpa:
    hibernate:
      ddl-auto: none #JPA를 통한 DDL 자동 생성 비활성화
  datasource:
    url: jdbc:mysql://localhost:3306/econavi_test
    username: econavi_test
    password: econaviTest
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always   # 항상 SQL 실행
      schema-locations: classpath:schema.sql
      continue-on-error: false #쿼리 실행 중 에러 발생 시 바로 종료 (시간 절약)
jwt:
  secret: 06412b0511818f29ebdb06e1ec8ce0afb8f2929646e32a4aac0206f6a5acbaf73826456718d61b9bdd9d40061132cf112a8b004fa4d30a6d8a082d65ad482356
  exp: 360000

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
